export enum ConstantBusiness {
  MOTORCYCLE_HOUR_VALUE = "MOTORCYCLE_HOUR_VALUE",
  MOTORCYCLE_DAY_VALUE = "MOTORCYCLE_DAY_VALUE",
  CYLINDER_CAPACITY_FOR_INCREMENT = "CYLINDER_CAPACITY_FOR_INCREMENT",
  INCREMENT_VALUE_BY_CYLINDER_CAPACITY = "INCREMENT_VALUE_BY_CYLINDER_CAPACITY",
  CAR_HOUR_VALUE = "CAR_HOUR_VALUE",
  CAR_DAY_VALUE = "CAR_DAY_VALUE",
}
