// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChargeParking: typeof import('./components/ChargeParking.vue')['default']
    FormRegisterVehicleEntry: typeof import('./components/FormRegisterVehicleEntry.vue')['default']
    FormRegisterVehicleExit: typeof import('./components/FormRegisterVehicleExit.vue')['default']
    ParkingSpace: typeof import('./components/ParkingSpace.vue')['default']
    RateSpace: typeof import('./components/RateSpace.vue')['default']
  }
}

export { }
